repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
        additional_dependencies: [black~=22.3, "black[jupyter]"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args: ["poutyne", "tests", "-rn"]
        additional_dependencies: [pylint==2.12.1]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: ["poutyne", "tests"]
        additional_dependencies: [flake8==4.0.1]
