name: Linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
        exclude:
          - python-version: "3.7"
            os: macos-latest
          - python-version: "3.8"
            os: macos-latest
          - python-version: "3.9"
            os: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r styling_requirements.txt
          pip install -r tests/requirements.txt
          pip install -e .
      - name: PyLint
        run: |
          pylint poutyne/ tests/
      - name: Flake8
        run: |
          flake8 poutyne/ tests/

  windowslinting:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          .  ./InvokeFunc.ps1
          Invoke-NativeCommand pip install -r requirements.txt
          Invoke-NativeCommand pip install -r styling_requirements.txt
          Invoke-NativeCommand pip install -r tests/requirements.txt
          Invoke-NativeCommand pip install -e .
      - name: PyLint
        run: |
          .  ./InvokeFunc.ps1
          Invoke-NativeCommand pylint poutyne/ tests/
      - name: Flake8
        run: |
          .  ./InvokeFunc.ps1
          Invoke-NativeCommand flake8 poutyne/ tests/
