name: CI/CD

on:
  push:
  pull_request:
  schedule:
    # Run the tests at 00:00 each week on Sunday
    - cron: "0 0 * * 0"

jobs:
  cicd-pipeline:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
        include:
          - python-version: "3.10"
            os: macos-latest
          - python-version: "3.10"
            os: windows-latest
    uses: ./.github/workflows/reusable-main.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
