name: Tests

on:
  push:
  pull_request:
  schedule:
    # Run the tests at 00:00 each week on Sunday
    - cron: "0 0 * * 0"

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.7"
            os: ubuntu-latest
          - python-version: "3.8"
            os: ubuntu-latest
          - python-version: "3.9"
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          python setup.py develop
      - name: Test with pytest
        run: |
          pytest
      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
